#include "Automapper.h"

#include "Log.h"
#include "Provinces/Province.h"

#include <ranges>
#include <wx/taskbarbutton.h>

void Automapper::registerMatch(const std::shared_ptr<Province>& srcProvince, const std::shared_ptr<Province>& targetProvince)
{
	const auto& srcProvinceID = srcProvince->ID;
	const auto& targetProvinceID = targetProvince->ID;

	if (sourceProvinceShares.contains(srcProvinceID))
	{
		if (sourceProvinceShares[srcProvinceID].contains(targetProvinceID))
		{
			sourceProvinceShares[srcProvinceID][targetProvinceID]++;
		}
		else
		{
			sourceProvinceShares[srcProvinceID][targetProvinceID] = 1;
		}
	}
	else
	{
		sourceProvinceShares[srcProvinceID][targetProvinceID] = 1;

		// When registering a new source province, update the cache of impassable source provinces.
		if (srcProvince->isImpassable())
		{
			srcImpassablesCache.insert(srcProvinceID);
		}
	}

	if (targetProvinceShares.contains(targetProvinceID))
	{
		if (targetProvinceShares[targetProvinceID].contains(srcProvinceID))
		{
			targetProvinceShares[targetProvinceID][srcProvinceID]++;
		}
		else
		{
			targetProvinceShares[targetProvinceID][srcProvinceID] = 1;
		}
	}
	else
	{
		targetProvinceShares[targetProvinceID][srcProvinceID] = 1;

		// When registering a new target province, update the cache of impassable target provinces.
		if (targetProvince->isImpassable())
		{
			tgtImpassablesCache.insert(targetProvinceID);
		}
	}
}

static std::map<int, std::string, std::greater<>> getHighestMatches(const std::map<std::string, int>& shares)
{
	// Flip the shares map to get the shares as keys, with descending order.
	std::map<int, std::string, std::greater<>> sharesMap;
	for (const auto& [provID, share]: shares)
	{
		sharesMap[share] = provID;
	}

	return sharesMap;
}

bool Automapper::canProvincesBeMapped(const std::string& srcProvID, const std::string& tgtProvID, const bool allowAddingToExistingLink) const
{
	const bool srcAlreadyMapped = alreadyMappedSrcProvincesCache.contains(srcProvID);
	const bool tgtAlreadyMapped = alreadyMappedTgtProvincesCache.contains(tgtProvID);

	if (!allowAddingToExistingLink && (srcAlreadyMapped || tgtAlreadyMapped))
	{
		return false;
	}

	// Avoid many-to-many mappings.
	if (srcAlreadyMapped && tgtAlreadyMapped)
	{
		return false;
	}

	if (const auto& tgtLink = activeVersion->getLinkForTargetProvince(tgtProvID))
	{
		// If link already has multiple targets and a different source, we can't add another source.
		if (tgtLink->getTargets().size() > 1)
		{
			for (const auto& srcProv: tgtLink->getSources())
			{
				if (srcProv->ID != srcProvID)
				{
					return false;
				}
			}
		}
	}

	if (const auto& srcLink = activeVersion->getLinkForSourceProvince(srcProvID))
	{
		// If link already has multiple sources and a different target, we can't add another target.
		if (srcLink->getSources().size() > 1)
		{
			for (const auto& tgtProv: srcLink->getTargets())
			{
				if (tgtProv->ID != tgtProvID)
				{
					return false;
				}
			}
		}
	}

	return true;
}

void Automapper::mapProvinces(const std::string& srcProvID, const std::string& tgtProvID)
{
	activeVersion->addAutogeneratedLink(srcProvID, tgtProvID);

	sourceProvinceShares[srcProvID].erase(tgtProvID);
	targetProvinceShares[tgtProvID].erase(srcProvID);

	alreadyMappedSrcProvincesCache.insert(srcProvID);
	alreadyMappedTgtProvincesCache.insert(tgtProvID);
}

void Automapper::cleanUpSourceProvinceShares()
{
	for (const auto& ID: alreadyMappedSrcProvincesCache)
	{
		sourceProvinceShares.erase(ID);
	}
}

void Automapper::cleanUpTargetProvinceShares()
{
	for (const auto& ID: alreadyMappedTgtProvincesCache)
	{
		targetProvinceShares.erase(ID);
	}
}

void Automapper::forUnmappedTargetsMapUnmappedSources()
{
	for (const auto& [tgtProvID, srcProvMatches]: targetProvinceShares)
	{
		if (tgtImpassablesCache.contains(tgtProvID))
			continue;

		auto highestSrcMatches = getHighestMatches(srcProvMatches);
		if (highestSrcMatches.empty())
			continue;

		const auto& srcProvID = highestSrcMatches.begin()->second;
		if (srcImpassablesCache.contains(srcProvID))
			continue;
		if (!canProvincesBeMapped(srcProvID, tgtProvID, false))
			continue;

		mapProvinces(srcProvID, tgtProvID);
	}
	cleanUpTargetProvinceShares();
}

void Automapper::forUnmappedSourcesMapUnmappedTargets()
{
	for (const auto& [srcProvID, tgtProvMatches]: sourceProvinceShares)
	{
		if (srcImpassablesCache.contains(srcProvID))
			continue;
		if (tgtProvMatches.empty())
			continue;

		auto highestTgtMatches = getHighestMatches(tgtProvMatches);
		if (highestTgtMatches.empty())
			continue;

		const auto& tgtProvID = highestTgtMatches.begin()->second;
		if (tgtImpassablesCache.contains(tgtProvID))
			continue;
		if (!canProvincesBeMapped(srcProvID, tgtProvID, false))
			continue;

		mapProvinces(srcProvID, tgtProvID);
	}
	cleanUpSourceProvinceShares();
}

void Automapper::forNonImpassableTargetsMapTryToMapFirstChoices()
{
	for (const auto& [tgtProvID, srcProvMatches]: targetProvinceShares)
	{
		if (tgtImpassablesCache.contains(tgtProvID))
			continue;

		auto highestSrcMatches = getHighestMatches(srcProvMatches);
		if (highestSrcMatches.empty())
			continue;

		const auto& srcProvID = highestSrcMatches.begin()->second;
		if (srcImpassablesCache.contains(srcProvID))
			continue;
		if (!canProvincesBeMapped(srcProvID, tgtProvID, true))
			continue;

		mapProvinces(srcProvID, tgtProvID);
	}
	cleanUpTargetProvinceShares();
}

void Automapper::forNonImpassableSourcesMapTryToMapFirstChoices()
{
	for (const auto& [srcProvID, tgtProvMatches]: sourceProvinceShares)
	{
		if (srcImpassablesCache.contains(srcProvID))
			continue;
		if (tgtProvMatches.empty())
			continue;

		auto highestTgtMatches = getHighestMatches(tgtProvMatches);
		if (highestTgtMatches.empty())
			continue;

		const auto& tgtProvID = highestTgtMatches.begin()->second;
		if (tgtImpassablesCache.contains(tgtProvID))
			continue;
		if (!canProvincesBeMapped(srcProvID, tgtProvID, true))
			continue;

		mapProvinces(srcProvID, tgtProvID);
	}
	cleanUpSourceProvinceShares();
}

void Automapper::forUnmappedTargetsEvaluateAllNonImpassableMatches()
{
	for (const auto& [tgtProvID, srcProvMatches]: targetProvinceShares)
	{
		if (tgtImpassablesCache.contains(tgtProvID))
			continue;
		if (srcProvMatches.empty())
			continue;

		auto highestSrcMatches = getHighestMatches(srcProvMatches);
		for (const auto& srcProvID: highestSrcMatches | std::views::values)
		{
			if (srcImpassablesCache.contains(srcProvID))
				continue;
			if (!canProvincesBeMapped(srcProvID, tgtProvID, true))
				continue;

			mapProvinces(srcProvID, tgtProvID);
			break;
		}
	}
	cleanUpTargetProvinceShares();
}

void Automapper::forUnmappedSourcesEvaluateAllNonImpassableMatches()
{
	for (const auto& [srcProvID, tgtProvMatches]: sourceProvinceShares)
	{
		if (srcImpassablesCache.contains(srcProvID))
			continue;
		if (tgtProvMatches.empty())
			continue;

		auto highestTgtMatches = getHighestMatches(tgtProvMatches);
		for (const auto& tgtProvID: highestTgtMatches | std::views::values)
		{
			if (tgtImpassablesCache.contains(tgtProvID))
				continue;
			if (!canProvincesBeMapped(srcProvID, tgtProvID, true))
				continue;

			mapProvinces(srcProvID, tgtProvID);
			break;
		}
	}
	cleanUpSourceProvinceShares();
}

void Automapper::forUnmappedTargetsEvaluateAllMatches()
{
	for (const auto& [tgtProvID, srcProvMatches]: targetProvinceShares)
	{
		auto highestSrcMatches = getHighestMatches(srcProvMatches);
		for (const auto& srcProvID: highestSrcMatches | std::views::values)
		{
			if (!canProvincesBeMapped(srcProvID, tgtProvID, true))
				continue;

			mapProvinces(srcProvID, tgtProvID);
			break;
		}
	}
	cleanUpTargetProvinceShares();
}

void Automapper::forUnmappedSourcesEvaluateAllMatches()
{
	for (const auto& [srcProvID, tgtProvMatches]: sourceProvinceShares)
	{
		auto highestTgtMatches = getHighestMatches(tgtProvMatches);
		for (const auto& tgtProvID: highestTgtMatches | std::views::values)
		{
			if (!canProvincesBeMapped(srcProvID, tgtProvID, true))
				continue;

			mapProvinces(srcProvID, tgtProvID);
			break;
		}
	}
	cleanUpSourceProvinceShares();
}

void Automapper::forUnmappedTargetsTryToStealSourcesFromExistingLinks()
{
	for (const auto& [tgtProvID, srcProvMatches]: targetProvinceShares)
	{
		if (tgtImpassablesCache.contains(tgtProvID))
			continue;

		auto highestSrcMatches = getHighestMatches(srcProvMatches);
		for (const auto& srcProvID: highestSrcMatches | std::views::values)
		{
			if (srcImpassablesCache.contains(srcProvID))
				continue;

			const auto& srcLinkToBeMugged = activeVersion->getLinkForSourceProvince(srcProvID);
			if (!srcLinkToBeMugged || srcLinkToBeMugged->getSources().size() <= 1)
				continue;

			Log(LogLevel::Debug) << "Stealing source province " << srcProvID << " from existing mapping that contains target province "
										<< srcLinkToBeMugged->getTargets()[0]->ID << " in order to map target province " << tgtProvID;
			activeVersion->activateLinkByID(srcLinkToBeMugged->getID());
			if (activeVersion->toggleProvinceByID(srcProvID, true) != std::nullopt)
			{
				// The function should have returned nullopt because we're not creating a new link.
				Log(LogLevel::Error) << "Failed to correctly remove province " << srcProvID << " from a link.";
			}
			mapProvinces(srcProvID, tgtProvID);
			break;
		}
	}
	cleanUpTargetProvinceShares();
}

void Automapper::forUnmappedSourcesTryToStealTargetsFromExistingLinks()
{
	for (const auto& [srcProvID, tgtProvMatches]: sourceProvinceShares)
	{
		if (srcImpassablesCache.contains(srcProvID))
			continue;

		auto highestTgtMatches = getHighestMatches(tgtProvMatches);
		for (const auto& tgtProvID: highestTgtMatches | std::views::values)
		{
			if (tgtImpassablesCache.contains(tgtProvID))
				continue;

			const auto& tgtLinkToBeMugged = activeVersion->getLinkForTargetProvince(tgtProvID);
			if (!tgtLinkToBeMugged || tgtLinkToBeMugged->getTargets().size() <= 1)
				continue;

			Log(LogLevel::Debug) << "Stealing target province " << tgtProvID << " from existing mapping that contains source province "
										<< tgtLinkToBeMugged->getSources()[0]->ID << " in order to map source province " << srcProvID;
			activeVersion->activateLinkByID(tgtLinkToBeMugged->getID());
			if (activeVersion->toggleProvinceByID(tgtProvID, false) != std::nullopt)
			{
				// The function should have returned nullopt because we're not creating a new link.
				Log(LogLevel::Error) << "Failed to correctly remove province " << tgtProvID << " from a link.";
			}
			mapProvinces(srcProvID, tgtProvID);
			break;
		}
	}
	cleanUpSourceProvinceShares();
}

void Automapper::generateLinks(wxTaskBarButton* taskBarBtn)
{
	// General rules for the automapping:
	// - We don't modify the hand-made links.
	// - Provinces belonging to hand-made links are excluded from the automapping.
	// - We don't create many-to-many mappings.

	activeVersion->deactivateLink();
	int currentProgress = 3;

	// 1. For all non-impassable target provinces:
	//	   If the most matching source province is available and not impassable, map them.
	//	   Require both sides to be currently unmapped.
	Log(LogLevel::Debug) << "Link generation step 1...";
	forUnmappedTargetsMapUnmappedSources();
	if (taskBarBtn)
		taskBarBtn->SetProgressValue(++currentProgress);

	// 2. For all yet unmapped non-impassable source provinces:
	//	   If the most matching target province is available and not impassable, map them.
	//	   Require both sides to be currently unmapped.
	Log(LogLevel::Debug) << "Link generation step 2...";
	forUnmappedSourcesMapUnmappedTargets();
	if (taskBarBtn)
		taskBarBtn->SetProgressValue(++currentProgress);

	// 3. For all non-impassable target provinces:
	//	   If the most matching source province is available and not impassable, map them.
	Log(LogLevel::Debug) << "Link generation step 3...";
	forNonImpassableTargetsMapTryToMapFirstChoices();
	if (taskBarBtn)
		taskBarBtn->SetProgressValue(++currentProgress);

	// 4. For all yet unmapped non-impassable source provinces:
	//	   If the most matching target province is available and not impassable, map them.
	Log(LogLevel::Debug) << "Link generation step 4...";
	forNonImpassableSourcesMapTryToMapFirstChoices();
	if (taskBarBtn)
		taskBarBtn->SetProgressValue(++currentProgress);

	// 5. For all yet unmapped non-impassable target provinces:
	//	   Try to use the most matching available non-impassable source province to map them.
	Log(LogLevel::Debug) << "Link generation step 5...";
	forUnmappedTargetsEvaluateAllNonImpassableMatches();
	if (taskBarBtn)
		taskBarBtn->SetProgressValue(++currentProgress);

	// 6. For all yet unmapped non-impassable source provinces:target
	//	   Try to use the most matching available non-impassable target province to map them.
	Log(LogLevel::Debug) << "Link generation step 6...";
	forUnmappedSourcesEvaluateAllNonImpassableMatches();
	if (taskBarBtn)
		taskBarBtn->SetProgressValue(++currentProgress);

	// 7. For all yet unmapped target provinces:
	//    Try to use the most matching available source province to map them.
	Log(LogLevel::Debug) << "Link generation step 7...";
	forUnmappedTargetsEvaluateAllMatches();
	if (taskBarBtn)
		taskBarBtn->SetProgressValue(++currentProgress);

	// 8. For all yet unmapped source provinces:
	//    Try to use the most matching available target province to map them.
	Log(LogLevel::Debug) << "Link generation step 8...";
	forUnmappedSourcesEvaluateAllMatches();
	if (taskBarBtn)
		taskBarBtn->SetProgressValue(++currentProgress);

	// 9. For all yet unmapped non-impassable target provinces, we're running out of options, so we turn to theft.
	//    Check if we can steal a source province from an existing many-to-one link.
	Log(LogLevel::Debug) << "Link generation step 9...";
	forUnmappedTargetsTryToStealSourcesFromExistingLinks();
	if (taskBarBtn)
		taskBarBtn->SetProgressValue(++currentProgress);

	// 10. For all yet unmapped non-impassable source provinces, we're running out of options, so we turn to theft.
	//     Check if we can steal a target province from an existing one-to-many link.
	Log(LogLevel::Debug) << "Link generation step 10...";
	forUnmappedSourcesTryToStealTargetsFromExistingLinks();
	if (taskBarBtn)
		taskBarBtn->SetProgressValue(++currentProgress);

	// After steps 9 and 10, it may be possible to map some provinces that were previously impossible to map.
	// Repeat steps 3 to 8.
	Log(LogLevel::Debug) << "Link generation step 11...";
	forNonImpassableTargetsMapTryToMapFirstChoices();
	if (taskBarBtn)
		taskBarBtn->SetProgressValue(++currentProgress);
	Log(LogLevel::Debug) << "Link generation step 12...";
	forNonImpassableSourcesMapTryToMapFirstChoices();
	if (taskBarBtn)
		taskBarBtn->SetProgressValue(++currentProgress);
	Log(LogLevel::Debug) << "Link generation step 13...";
	forUnmappedTargetsEvaluateAllNonImpassableMatches();
	if (taskBarBtn)
		taskBarBtn->SetProgressValue(++currentProgress);
	Log(LogLevel::Debug) << "Link generation step 14...";
	forUnmappedSourcesEvaluateAllNonImpassableMatches();
	if (taskBarBtn)
		taskBarBtn->SetProgressValue(++currentProgress);
	Log(LogLevel::Debug) << "Link generation step 15...";
	forUnmappedTargetsEvaluateAllMatches();
	if (taskBarBtn)
		taskBarBtn->SetProgressValue(++currentProgress);
	Log(LogLevel::Debug) << "Link generation step 16...";
	forUnmappedSourcesEvaluateAllMatches();
	if (taskBarBtn)
		taskBarBtn->SetProgressValue(++currentProgress);

	Log(LogLevel::Info) << "<> Automapping complete.";
}
