#include "MainFrame.h"
#include "CommonFunctions.h"
#include "Images/ImageCanvas.h"
#include "Images/ImageFrame.h"
#include "Links/LinksFrame.h"
#include "Log.h"
#include "OSCompatibilityLayer.h"
#include "wx/splitter.h"
#include <fstream>
#include <wx/filepicker.h>
#include <wx/rawbmp.h>

MainFrame::MainFrame(const wxString& title, const wxPoint& pos, const wxSize& size): wxFrame(nullptr, wxID_ANY, title, pos, size)
{
	Bind(wxEVT_MENU, &MainFrame::onExit, this, wxID_EXIT);
	Bind(wxEVT_MENU, &MainFrame::onAbout, this, wxID_ABOUT);
	Bind(wxEVT_MENU, &MainFrame::onSupportUs, this, wxID_NETWORK);
	Bind(wxEVT_MENU, &MainFrame::onSaveLinks, this, wxID_SAVE); // This one is generated by the menu in links frame. It travels.
}

void MainFrame::initFrame()
{
	configuration.load();
	SetBackgroundColour(wxColour(230, 230, 230));
	sizer = new wxFlexGridSizer(3, 2, 5);
	SetSizer(sizer);

	// Source directory
	auto* sdirText = new wxStaticText(this, wxID_ANY, "Source Directory", wxDefaultPosition);
	sourceDirPicker = new wxDirPickerCtrl(this, 0, wxEmptyString, "BROWSE", wxDefaultPosition, wxSize(350, wxDefaultCoord), wxFLP_USE_TEXTCTRL | wxFLP_SMALL);
	sourceDirPicker->Bind(wxEVT_DIRPICKER_CHANGED, &MainFrame::onPathChanged, this);
	sourceDirStatus = new wxWindow(this, wxID_ANY, wxDefaultPosition, wxSize(15, 15));

	sizer->Add(sdirText, 0, wxLEFT | wxRIGHT | wxALIGN_CENTER_VERTICAL, 5);
	sizer->Add(sourceDirPicker, 0, wxLEFT | wxRIGHT | wxEXPAND | wxALIGN_CENTER_VERTICAL, 5);
	sizer->Add(sourceDirStatus, 0, wxLEFT | wxRIGHT | wxALIGN_CENTER_VERTICAL, 5);

	// Target Directory
	auto* tdirText = new wxStaticText(this, wxID_ANY, "Target Directory", wxDefaultPosition);
	targetDirPicker = new wxDirPickerCtrl(this, 1, wxEmptyString, "BROWSE", wxDefaultPosition, wxSize(350, wxDefaultCoord), wxFLP_USE_TEXTCTRL | wxFLP_SMALL);
	targetDirPicker->Bind(wxEVT_DIRPICKER_CHANGED, &MainFrame::onPathChanged, this);
	targetDirStatus = new wxWindow(this, wxID_ANY, wxDefaultPosition, wxSize(15, 15));

	sizer->Add(tdirText, 0, wxLEFT | wxRIGHT | wxALIGN_CENTER_VERTICAL, 5, nullptr);
	sizer->Add(targetDirPicker, 0, wxLEFT | wxRIGHT | wxEXPAND | wxALIGN_CENTER_VERTICAL, 5, nullptr);
	sizer->Add(targetDirStatus, 0, wxLEFT | wxRIGHT | wxALIGN_CENTER_VERTICAL, 5);

	// Link File
	auto* linkFileText = new wxStaticText(this, wxID_ANY, "Link File", wxDefaultPosition);
	linkFilePicker =
		 new wxFilePickerCtrl(this, 2, wxEmptyString, "BROWSE", "*.txt", wxDefaultPosition, wxSize(350, wxDefaultCoord), wxFLP_USE_TEXTCTRL | wxFLP_SMALL);
	linkFilePicker->Bind(wxEVT_FILEPICKER_CHANGED, &MainFrame::onPathChanged, this);
	linkFileStatus = new wxWindow(this, wxID_ANY, wxDefaultPosition, wxSize(15, 15));

	sizer->Add(linkFileText, 0, wxLEFT | wxRIGHT | wxALIGN_CENTER_VERTICAL, 5, nullptr);
	sizer->Add(linkFilePicker, 0, wxLEFT | wxRIGHT | wxEXPAND | wxALIGN_CENTER_VERTICAL, 5, nullptr);
	sizer->Add(linkFileStatus, 0, wxLEFT | wxRIGHT | wxALIGN_CENTER_VERTICAL, 5);

	// Source Token
	auto* sourceTokenText = new wxStaticText(this, wxID_ANY, "Source Token", wxDefaultPosition);
	sourceTokenField = new wxTextCtrl(this, 3, wxEmptyString, wxDefaultPosition, wxDefaultSize, wxBORDER_DEFAULT);
	sourceTokenField->Bind(wxEVT_TEXT, &MainFrame::onTokenChanged, this);
	sourceTokenStatus = new wxWindow(this, wxID_ANY, wxDefaultPosition, wxSize(15, 15));

	sizer->Add(sourceTokenText, 0, wxLEFT | wxRIGHT | wxALIGN_CENTER_VERTICAL, 5, nullptr);
	sizer->Add(sourceTokenField, 0, wxLEFT | wxRIGHT | wxEXPAND | wxALIGN_CENTER_VERTICAL, 5, nullptr);
	sizer->Add(sourceTokenStatus, 0, wxLEFT | wxRIGHT | wxALIGN_CENTER_VERTICAL, 5);

	// Target Token
	auto* targetTokenText = new wxStaticText(this, wxID_ANY, "Target Token", wxDefaultPosition);
	targetTokenField = new wxTextCtrl(this, 4, wxEmptyString, wxDefaultPosition, wxDefaultSize, wxBORDER_DEFAULT);
	targetTokenField->Bind(wxEVT_TEXT, &MainFrame::onTokenChanged, this);
	targetTokenStatus = new wxWindow(this, wxID_ANY, wxDefaultPosition, wxSize(15, 15));

	sizer->Add(targetTokenText, 0, wxLEFT | wxRIGHT | wxALIGN_CENTER_VERTICAL, 5, nullptr);
	sizer->Add(targetTokenField, 0, wxLEFT | wxRIGHT | wxEXPAND | wxALIGN_CENTER_VERTICAL, 5, nullptr);
	sizer->Add(targetTokenStatus, 0, wxLEFT | wxRIGHT | wxALIGN_CENTER_VERTICAL, 5);

	// The Button
	startButton = new wxButton(this, wxID_ANY, "Begin!", wxDefaultPosition, wxDefaultSize);
	startButton->Bind(wxEVT_COMMAND_BUTTON_CLICKED, &MainFrame::onStartButton, this);
	startButton->Disable();

	sizer->AddStretchSpacer(0);
	sizer->Add(startButton, wxSizerFlags(1).Top().CenterHorizontal());
	sizer->AddStretchSpacer(0);

	populateFrame();
}

void MainFrame::populateFrame()
{
	std::string path;
	std::wstring path16;

	// Source path
	if (configuration.getSourceDir())
	{
		path = *configuration.getSourceDir();
		path16 = commonItems::convertUTF8ToUTF16(path);
	}
	sourceDirPicker->SetPath(path16);
	sourceDirPicker->SetInitialDirectory(path16);
	auto bootEvent0 = wxFileDirPickerEvent(wxEVT_FILEPICKER_CHANGED, this, 0, path16);
	onPathChanged(bootEvent0);

	// target path
	if (configuration.getTargetDir())
	{
		path = *configuration.getTargetDir();
		path16 = commonItems::convertUTF8ToUTF16(path);
	}
	targetDirPicker->SetPath(path16);
	targetDirPicker->SetInitialDirectory(path16);
	auto bootEvent1 = wxFileDirPickerEvent(wxEVT_FILEPICKER_CHANGED, this, 1, path16);
	onPathChanged(bootEvent1);

	// source token
	std::string token;
	if (configuration.getSourceToken())
		token = *configuration.getSourceToken();
	sourceTokenField->SetValue(token);
	auto bootEvent3 = wxCommandEvent(wxEVT_NULL, 3);
	onTokenChanged(bootEvent3);

	// target token
	if (configuration.getTargetToken())
		token = *configuration.getTargetToken();
	targetTokenField->SetValue(token);
	auto bootEvent4 = wxCommandEvent(wxEVT_NULL, 4);
	onTokenChanged(bootEvent4);

	// links file goes last, because it can overwrite tokens if those aren't already loaded.
	std::wstring initialPath;
	if (configuration.getLinkFile())
	{
		path = *configuration.getLinkFile();
		path16 = commonItems::convertUTF8ToUTF16(path);
		const auto rawFile = trimPath(path);
		const auto rawPath = path.substr(0, rawFile.size());
		initialPath = commonItems::convertUTF8ToUTF16(rawPath);		
	}
	linkFilePicker->SetPath(path16);
	linkFilePicker->SetInitialDirectory(initialPath);
	auto bootEvent2 = wxFileDirPickerEvent(wxEVT_FILEPICKER_CHANGED, this, 2, path16);
	onPathChanged(bootEvent2);
}

void MainFrame::initLinksFrame()
{
	linksFrame = new LinksFrame(this, linkMapper.getVersions(), linkMapper.getActiveVersion());
	auto* menuDropDown = new wxMenu;
	menuDropDown->Append(wxID_SAVE, "Save Links");
	auto* linksMenuBar = new wxMenuBar;
	linksMenuBar->Append(menuDropDown, "&Save");
	linksFrame->SetMenuBar(linksMenuBar);
	linksFrame->Show();
}

void MainFrame::initImageFrame()
{
	sourceDefs.loadDefinitions(*configuration.getSourceDir() + "/definition.csv");
	Log(LogLevel::Info) << "Loaded " << sourceDefs.getProvinces().size() << " source provinces.";
	targetDefs.loadDefinitions(*configuration.getTargetDir() + "/definition.csv");
	Log(LogLevel::Info) << "Loaded " << targetDefs.getProvinces().size() << " target provinces.";

	linkMapper.loadMappings(linksFileString, sourceDefs, targetDefs, *configuration.getSourceToken(), *configuration.getTargetToken());
	const auto& activeLinks = linkMapper.getActiveVersion()->getLinks();
	Log(LogLevel::Info) << "Loaded " << activeLinks->size() << " active links.";

	// Import pixels.
	sourceImg = new wxImage();
	if (commonItems::DoesFileExist(*configuration.getSourceDir() + "/provinces.bmp"))
		sourceImg->LoadFile(*configuration.getSourceDir() + "/provinces.bmp", wxBITMAP_TYPE_BMP);
	else if (commonItems::DoesFileExist(*configuration.getSourceDir() + "/provinces.png"))
		sourceImg->LoadFile(*configuration.getSourceDir() + "/provinces.png", wxBITMAP_TYPE_PNG);
	readPixels(ImageTabSelector::SOURCE, *sourceImg);
	Log(LogLevel::Info) << "Registered " << sourceImg->GetSize().GetX() << "x" << sourceImg->GetSize().GetY() << " source pixels.";

	targetImg = new wxImage();
	if (commonItems::DoesFileExist(*configuration.getTargetDir() + "/provinces.bmp"))
		targetImg->LoadFile(*configuration.getTargetDir() + "/provinces.bmp", wxBITMAP_TYPE_BMP);
	else if (commonItems::DoesFileExist(*configuration.getTargetDir() + "/provinces.png"))
		targetImg->LoadFile(*configuration.getTargetDir() + "/provinces.png", wxBITMAP_TYPE_PNG);
	readPixels(ImageTabSelector::TARGET, *targetImg);
	Log(LogLevel::Info) << "Registered " << targetImg->GetSize().GetX() << "x" << targetImg->GetSize().GetY() << " target pixels.";

	imageFrame = new ImageFrame(this, linkMapper.getActiveVersion(), sourceImg, targetImg);
	auto* menuDropDown = new wxMenu;
	menuDropDown->Append(wxID_REVERT, "Toggle Orientation");
	menuDropDown->Append(wxID_BOLD, "Toggle The Shade");
	auto* imageMenuBar = new wxMenuBar;
	imageMenuBar->Append(menuDropDown, "&Image");
	imageFrame->SetMenuBar(imageMenuBar);

	imageFrame->Show();
}

void MainFrame::onExit(wxCommandEvent& event)
{
	Close(true);
}

void MainFrame::onAbout(wxCommandEvent& event)
{
	wxMessageBox(
		 "Copyright (c) 2020 The Paradox Game Converters Group\n\nThis tool, as all others, is free and available at our Github repository.\n\nGithub. Forums. "
		 "Wiki pages. Steam. If you need to find us, report bugs, offer suggestions or wish to participate, we're there.",
		 "Paradox Game Converters Group - Map Adjuster",
		 wxOK | wxICON_INFORMATION);
}

void MainFrame::onSupportUs(wxCommandEvent& event)
{
	wxLaunchDefaultBrowser("https://www.patreon.com/ParadoxGameConverters");
}

void MainFrame::readPixels(ImageTabSelector selector, const wxImage& img)
{
	unsigned char* rgb = img.GetData();
	for (auto y = 0; y < img.GetSize().GetY(); y++)
		for (auto x = 0; x < img.GetSize().GetX(); x++)
		{
			auto border = true;
			// border or regular pixel?
			if (isSameColorAtCoords(x, y, x - 1, y, img) && isSameColorAtCoords(x, y, x + 1, y, img) && isSameColorAtCoords(x, y, x, y - 1, img) &&
				 isSameColorAtCoords(x, y, x, y + 1, img))
				border = false;
			const auto offs = coordsToOffset(x, y, img.GetSize().GetX());

			if (selector == ImageTabSelector::SOURCE && border == true)
				sourceDefs.registerBorderPixel(x, y, rgb[offs], rgb[offs + 1], rgb[offs + 2]);
			else if (selector == ImageTabSelector::SOURCE && border == false)
				sourceDefs.registerPixel(x, y, rgb[offs], rgb[offs + 1], rgb[offs + 2]);
			else if (selector == ImageTabSelector::TARGET && border == true)
				targetDefs.registerBorderPixel(x, y, rgb[offs], rgb[offs + 1], rgb[offs + 2]);
			else if (selector == ImageTabSelector::TARGET && border == false)
				targetDefs.registerPixel(x, y, rgb[offs], rgb[offs + 1], rgb[offs + 2]);
		}
}

bool MainFrame::isSameColorAtCoords(const int ax, const int ay, const int bx, const int by, const wxImage& img)
{
	const auto height = img.GetSize().GetY();
	const auto width = img.GetSize().GetX();
	if (ax > width - 1 || ax < 0 || bx > width - 1 || bx < 0)
		return false;
	if (ay > height - 1 || ay < 0 || by > height - 1 || by < 0)
		return false;
	const auto offsetA = coordsToOffset(ax, ay, width);
	const auto offsetB = coordsToOffset(bx, by, width);
	unsigned char* rgb = img.GetData();
	if (rgb[offsetA] == rgb[offsetB] && rgb[offsetA + 1] == rgb[offsetB + 1] && rgb[offsetA + 2] == rgb[offsetB + 2])
		return true;
	else
		return false;
}

int MainFrame::coordsToOffset(int x, int y, int width)
{
	return (y * width + x) * 3;
}

void MainFrame::onPathChanged(wxFileDirPickerEvent& evt)
{
	const auto validPath = commonItems::DoesFolderExist(commonItems::UTF16ToUTF8(evt.GetPath().ToStdWstring()));
	const auto result = commonItems::UTF16ToUTF8(evt.GetPath().ToStdWstring());
	const auto green = wxColour(130, 250, 130);
	const auto red = wxColour(250, 130, 130);

	// source path
	if (evt.GetId() == 0)
	{
		if (validPath && (commonItems::DoesFileExist(result + "/provinces.bmp") || commonItems::DoesFileExist(result + "/provinces.png")))
		{
			sourceDirStatus->SetBackgroundColour(green);
			sanity[0] = true;
		}
		else
		{
			sourceDirStatus->SetBackgroundColour(red);
			sanity[0] = false;
		}
		configuration.setSourceDir(result);
	}
	// target path
	else if (evt.GetId() == 1)
	{
		if (validPath && (commonItems::DoesFileExist(result + "/provinces.bmp") || commonItems::DoesFileExist(result + "/provinces.png")))
		{
			targetDirStatus->SetBackgroundColour(green);
			sanity[1] = true;
		}
		else
		{
			targetDirStatus->SetBackgroundColour(red);
			sanity[1] = false;
		}
		configuration.setTargetDir(result);
	}
	// links file
	else if (evt.GetId() == 2)
	{
		if (commonItems::DoesFileExist(result))
		{
			linkFileStatus->SetBackgroundColour(green);
			std::ifstream linksFile(result);
			if (linksFile.is_open())
				linksFileString.assign(std::istreambuf_iterator<char>(linksFile), std::istreambuf_iterator<char>());
			linksFile.close();
			sanity[2] = true;
			auto bootEvent3 = wxCommandEvent(wxEVT_NULL, 3);
			onTokenChanged(bootEvent3);
			auto bootEvent4 = wxCommandEvent(wxEVT_NULL, 4);
			onTokenChanged(bootEvent4);
		}
		else
		{
			linkFileStatus->SetBackgroundColour(red);
			linksFileString.clear();
			sanity[2] = false;
			auto bootEvent3 = wxCommandEvent(wxEVT_NULL, 3);
			onTokenChanged(bootEvent3);
			auto bootEvent4 = wxCommandEvent(wxEVT_NULL, 4);
			onTokenChanged(bootEvent4);
		}
		configuration.setLinkFile(result);
	}
	configuration.save();
	applySanityToButton();
	Refresh();
}

void MainFrame::onTokenChanged(wxCommandEvent& evt)
{
	const auto green = wxColour(130, 250, 130);
	const auto red = wxColour(250, 130, 130);

	// source token
	if (evt.GetId() == 3)
	{
		const auto input = sourceTokenField->GetValue();
		const auto rawinput = commonItems::UTF16ToUTF8(input.ToStdWstring());
		if (!rawinput.empty() && rawinput.size() >= 2 && linksFileString.find(rawinput) != std::string::npos)
		{
			sourceTokenStatus->SetBackgroundColour(green);
			sanity[3] = true;
		}
		else
		{
			sourceTokenStatus->SetBackgroundColour(red);
			sanity[3] = false;
		}
		configuration.setSourceToken(rawinput);
	}
	// target token
	else if (evt.GetId() == 4)
	{
		const auto input = targetTokenField->GetValue();
		const auto rawinput = commonItems::UTF16ToUTF8(input.ToStdWstring());
		if (!rawinput.empty() && rawinput.size() >= 2 && linksFileString.find(rawinput) != std::string::npos)
		{
			targetTokenStatus->SetBackgroundColour(green);
			sanity[4] = true;
		}
		else
		{
			targetTokenStatus->SetBackgroundColour(red);
			sanity[4] = false;
		}
		configuration.setTargetToken(rawinput);
	}
	configuration.save();
	applySanityToButton();
	Refresh();
}

void MainFrame::applySanityToButton()
{
	if (sanity[0] && sanity[1] && sanity[2] && sanity[3] && sanity[4])
		startButton->Enable();
	else
		startButton->Disable();
}

void MainFrame::onStartButton(wxCommandEvent& evt)
{
	startButton->Disable();
	Refresh();
	initImageFrame();
	initLinksFrame();
	Hide();
}

void MainFrame::onSaveLinks(wxCommandEvent& evt)
{
	linkMapper.exportMappings(*configuration.getLinkFile());
	wxMessageBox("Links saved.", "Save");
}
